name: Process issue
on:
  issues:
    types:
      - labeled
      - unlabeled
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  extract-values:
    if: ${{ github.event.issue.state == 'open' && contains(github.event.issue.title, 'Request new module:') && !contains( github.event.issue.labels.*.name, 'repo_created') }}
    runs-on: ubuntu-latest
    steps:
      - id: variables
        name: Extract info from issue
        uses: cloud-native-toolkit/action-repo-issue-extractor@main
        with:
          token: ${{ secrets.GIT_ADMIN_TOKEN }}
    outputs:
      type: ${{ steps.variables.outputs.type }}
      name: ${{ steps.variables.outputs.name }}
      displayName: ${{ steps.variables.outputs.displayName }}
      provider: ${{ steps.variables.outputs.provider }}
      softwareProvider: ${{ steps.variables.outputs.softwareProvider }}
      group: ${{ steps.variables.outputs.group }}
      category: ${{ steps.variables.outputs.category }}
      approved: ${{ steps.variables.outputs.approved }}
      requester: ${{ steps.variables.outputs.requester }}
      issue_number: ${{ steps.variables.outputs.issue_number }}
      new_module: ${{ steps.variables.outputs.new_module }}

  error-extract-values:
    runs-on: ubuntu-latest
    needs: extract-values
    if: always() && needs.extract-values.result == 'failure'
    

    steps:
    - name: Add comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: "Error extracting values. See details at: https://github.com/cloud-native-toolkit/automation-modules/actions/runs/${{ github.run_id }}"

  create-repo:
    runs-on: ubuntu-latest
    needs: extract-values
    if: ${{ needs.extract-values.outputs.approved == 'true' && needs.extract-values.outputs.new_module == 'true' }}

    steps:
      - id: create
        name: Create repo
        uses: cloud-native-toolkit/action-module-create@main
        with:
          token: ${{ secrets.GIT_ADMIN_TOKEN }}
          type: ${{ needs.extract-values.outputs.type }}
          name: ${{ needs.extract-values.outputs.name }}
          displayName: ${{ needs.extract-values.outputs.displayName }}
          provider: ${{ needs.extract-values.outputs.provider }}
          softwareProvider: ${{ needs.extract-values.outputs.softwareProvider }}
          strict: true
    outputs:
      repoUrl: ${{ steps.create.outputs.repo_url }}
      issue_number: ${{ needs.extract-values.outputs.issue_number }}
      owner: ${{ steps.create.outputs.owner }}
      repo: ${{ steps.create.outputs.repo }}
      moduleName: ${{ steps.create.outputs.moduleName }}
      displayName: ${{ steps.create.outputs.displayName }}
      cloudProvider: ${{ steps.create.outputs.cloudProvider }}
      softwareProvider: ${{ steps.create.outputs.softwareProvider }}
      group: ${{ needs.extract-values.outputs.group }}
      category: ${{ needs.extract-values.outputs.category }}

  error-create-repo:
    runs-on: ubuntu-latest
    needs: create-repo
    if: always() && needs.create-repo.result == 'failure'

    steps:
    - name: Add comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: "Error creating repo. See details at: https://github.com/cloud-native-toolkit/automation-modules/actions/runs/${{ github.run_id }}"


  label_issues:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
      - name: Label issue
        uses: andymckay/labeler@master
        with:
          add-labels: "repo_created"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body:  Created repo - ${{ needs.create-repo.outputs.repoUrl }}


  add-to-catalog:
    runs-on: ubuntu-latest
    needs: create-repo

    steps:
      - uses: actions/checkout@v2

      - name: Update catalog module
        uses: cloud-native-toolkit/action-add-to-catalog@main
        with:
          repoUrl: ${{ needs.create-repo.outputs.repoUrl }}
          category: ${{ needs.create-repo.outputs.category }}
          name: ${{ needs.create-repo.outputs.moduleName }}
          displayName: ${{ needs.create-repo.outputs.displayName }}
          group: ${{ needs.create-repo.outputs.group }}
          cloudProvider: ${{ needs.create-repo.outputs.cloudProvider }}
          softwareProvider: ${{ needs.create-repo.outputs.softwareProvider }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Cloud-Native Toolkit
          author_email: cloud-native-toolkit@ibm.com
          message: 'Adds entry to module catalog'
          add: 'catalog.yaml'
          pull_strategy: 'NO-PULL'

      - name: Label issue
        uses: andymckay/labeler@master
        with:
          add-labels: "added_to_catalog"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
